// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo9dRWXRiMi4PYrGeuo8zHnFNZ4_KWXs4',
    appId: '1:383388078416:web:160715aebd1e10df9b9c55',
    messagingSenderId: '383388078416',
    projectId: 'instagram-lite-vikas',
    authDomain: 'instagram-lite-vikas.firebaseapp.com',
    storageBucket: 'instagram-lite-vikas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZqh2K2nHNzMMvghaIwYoretvRBuFx6x0',
    appId: '1:383388078416:android:fcf2ac081125ed9f9b9c55',
    messagingSenderId: '383388078416',
    projectId: 'instagram-lite-vikas',
    storageBucket: 'instagram-lite-vikas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMZ_Da6XcX9znJ5-5_qYZqOUmkOBXOzHI',
    appId: '1:383388078416:ios:938c64ef609a048c9b9c55',
    messagingSenderId: '383388078416',
    projectId: 'instagram-lite-vikas',
    storageBucket: 'instagram-lite-vikas.firebasestorage.app',
    iosBundleId: 'com.vikas.instagramLite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMZ_Da6XcX9znJ5-5_qYZqOUmkOBXOzHI',
    appId: '1:383388078416:ios:938c64ef609a048c9b9c55',
    messagingSenderId: '383388078416',
    projectId: 'instagram-lite-vikas',
    storageBucket: 'instagram-lite-vikas.firebasestorage.app',
    iosBundleId: 'com.vikas.instagramLite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo9dRWXRiMi4PYrGeuo8zHnFNZ4_KWXs4',
    appId: '1:383388078416:web:7a7c729d750bb4269b9c55',
    messagingSenderId: '383388078416',
    projectId: 'instagram-lite-vikas',
    authDomain: 'instagram-lite-vikas.firebaseapp.com',
    storageBucket: 'instagram-lite-vikas.firebasestorage.app',
  );
}
